version: '3.8'

networks:
  red-backbone:
    driver: bridge

volumes:
  postgres_data:

services:
  # 1. Servidor Web Nginx (Proxy Inverso Frontal)
  web-server:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - node-service
    networks:
      - red-backbone

  # 2. Servidor de Aplicaciones Node.js (API Nativa Seguro)
  node-service:
    build: ./node-app
    container_name: node_app
    expose:
      - "3000"
    networks:
      - red-backbone

  # 3. Servidor de Base de Datos PostgreSQL
  database-sql:
    image: postgres:15-alpine
    container_name: database_sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-backbone

  # 4. Administrador Web pgAdmin4
  pgadmin-dashboard:
    image: dpage/pgadmin4
    container_name: pgadmin_dashboard
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - database-sql
    networks:
      - red-backbone

  # 5. Entorno de Ciencia de Datos Jupyter Notebook
  jupyter-workspace:
    image: jupyter/base-notebook
    container_name: jupyter_workspace
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    volumes:
      - ./jupyter_notebooks:/home/jovyan/work
    networks:
      - red-backbone
